website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

namespace website.Controllers
{
	/// <summary>
	/// Home controller.
	/// Display information about me.
	/// </summary>
	public class HomeController : Controller
	{
		/// <summary>
		/// Default route.
		/// </summary>
		public ActionResult Index()
		{
			ViewBag.Section = "about";

			return View();
		}
	}
}

website/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using website.Models;
using website.Utilities;
using System.IO;
using website.Data;

namespace website.Controllers
{
	/// <summary>
	/// Skills controller.
	/// Display my skills.
	/// </summary>
	public class SkillsController : Controller
	{
		/// <summary>
		/// The skills repository.
		/// </summary>
		private SkillsRepository _skillsRepository = null;

		/// <summary>
		/// Initializes a new instance of the <see cref="website.Controllers.SkillsController"/> class.
		/// </summary>
		public SkillsController()
		{
			_skillsRepository = new SkillsRepository();
		}

		/// <summary>
		/// Default route for the skills controller.
		/// </summary>
		public ActionResult Index()
		{					
			return View(_skillsRepository.GetSkills());
		}
	}
}

website/Views/Home/Index.cshtml
@section AdditionalMeta
{
	<script type="application/ld+json">
	{
	  	"@@context": "http://schema.org",
	  	"@@type": "Person",
	  	"name": "Matt Gaikema",
	  	"url": "http://www.mattgaikema.com/",
	 	"description": "Personal website for Matt Gaikema",
	 	"email": "mailto:mgaikema1@gmail.com",
	 	"alumniOf": "Texas A&M University",
	 	"image": "@Url.Content("~/Content/media/me.jpg")"
	}
	</script>
	<script>
		document.title = "Matt Gaikema";
	</script>
}

<div id='about' class="container panel panel-default">
	<div class="panel-heading">
		<h2 class="page-title">Matt Gaikema</h2>
	</div>
	<div class="panel-body">
		<div class="media">
			<div class="media-left">
				<img class="media-object"  id="me" alt="Matt Gaikema" src="@Url.Content("~/Content/media/me.jpg")">
			</div><!--media-left-->
			<div class="media-body">
				<h3 class="media-heading">About Me</h3>
				<p>
				My name is Matt Gaikema, and I am a junior pursuing a double major in Computer Science and Applied Mathematics
				at Texas A&M.
				I am fascinated by the close connection between mathematics and computer science,
				and enjoy researching and solving problems.
				I mostly program in C++, C#, and Mathematica, but have experience with  @Html.ActionLink("other skills", "Index", "Skills") as well.
				</p>
				<p>
				When I'm not programming, I enjoy running, reading, 
				and playing with my three dogs, Apple, Lucy, and Kiwi.
				</p>
			</div><!--media-body-->
		</div><!--media-->
	</div>

</div><!--About-->